/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jupnp_igd_tools;

import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.ParseException;
import org.apache.commons.cli.HelpFormatter;

public class CLI {

    protected Options options;

    public CLI() {
        options = buildCommandLine();
    }

    public CommandLine parse(String[] args) throws ParseException {
        CommandLineParser parser = new DefaultParser();
        return parser.parse(options, args);
    }

    public void printUsageText(String name) {
        HelpFormatter formatter = new HelpFormatter();
        formatter.printHelp(name, options);
    }

    private static Options buildCommandLine() {
        Options options = new Options();
        options.addOption(Option.builder("h")
                                .longOpt("help")
                                .desc("Print usage help text")
                                .hasArg(false)
                                .build());
        options.addOption(Option.builder("r")
                                .longOpt("print-registry")
                                .desc("Print the contents of the registry after 10 seconds of discovery")
                                .hasArg(false)
                                .build());
        options.addOption(Option.builder("e")
                                .longOpt("query-external-ip")
                                .desc("Query the IGD for the external IP address")
                                .build());

        return options;
    }

}
